/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CharacterId = string;
export interface CharacterProfile {
  'id' : CharacterId,
  'owner' : UserId,
  'appearance' : string,
  'name' : string,
  'description' : string,
  'avatarImageUrl' : [] | [string],
  'serverId' : [] | [ServerId],
}
export interface RoleplayPost {
  'id' : RoleplayPostId,
  'content' : string,
  'author' : UserId,
  'timestamp' : bigint,
  'roomId' : RoomId,
}
export type RoleplayPostId = bigint;
export interface Room {
  'id' : RoomId,
  'creator' : UserId,
  'members' : Array<UserId>,
  'name' : string,
  'description' : string,
  'roleplayPosts' : Array<RoleplayPost>,
  'serverId' : ServerId,
}
export type RoomId = string;
export interface Server {
  'id' : ServerId,
  'owner' : UserId,
  'name' : string,
  'description' : string,
  'bannerImageUrl' : [] | [string],
  'memberships' : Array<ServerMembership>,
  'rooms' : Array<Room>,
}
export type ServerId = string;
export interface ServerMembership { 'userId' : UserId, 'role' : ServerRole }
export type ServerRole = { 'member' : null } |
  { 'admin' : null } |
  { 'owner' : null };
export type UserId = Principal;
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCharacterProfile' : ActorMethod<[CharacterProfile], undefined>,
  'createRoleplayPost' : ActorMethod<[ServerId, RoomId, string], undefined>,
  'createRoom' : ActorMethod<[ServerId, RoomId, string, string], undefined>,
  'createServer' : ActorMethod<
    [ServerId, string, string, [] | [string]],
    undefined
  >,
  'deleteRoleplayPost' : ActorMethod<
    [ServerId, RoomId, RoleplayPostId],
    undefined
  >,
  'editCharacterProfile' : ActorMethod<[CharacterProfile], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacterProfile' : ActorMethod<[CharacterId], CharacterProfile>,
  'getRoleplayPost' : ActorMethod<
    [ServerId, RoomId, RoleplayPostId],
    RoleplayPost
  >,
  'getRoom' : ActorMethod<[ServerId, RoomId], Room>,
  'getServer' : ActorMethod<[ServerId], Server>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinServer' : ActorMethod<[ServerId], undefined>,
  'leaveServer' : ActorMethod<[ServerId], undefined>,
  'listCharacterProfiles' : ActorMethod<
    [UserId, [] | [ServerId]],
    Array<CharacterProfile>
  >,
  'listRoleplayPosts' : ActorMethod<[ServerId, RoomId], Array<RoleplayPost>>,
  'listRooms' : ActorMethod<[ServerId], Array<Room>>,
  'listServers' : ActorMethod<[], Array<Server>>,
  'removeMember' : ActorMethod<[ServerId, UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateServer' : ActorMethod<
    [ServerId, string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];