/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CharacterId = IDL.Text;
export const UserId = IDL.Principal;
export const ServerId = IDL.Text;
export const CharacterProfile = IDL.Record({
  'id' : CharacterId,
  'owner' : UserId,
  'appearance' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'avatarImageUrl' : IDL.Opt(IDL.Text),
  'serverId' : IDL.Opt(ServerId),
});
export const RoomId = IDL.Text;
export const RoleplayPostId = IDL.Nat;
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const RoleplayPost = IDL.Record({
  'id' : RoleplayPostId,
  'content' : IDL.Text,
  'author' : UserId,
  'timestamp' : IDL.Int,
  'roomId' : RoomId,
});
export const Room = IDL.Record({
  'id' : RoomId,
  'creator' : UserId,
  'members' : IDL.Vec(UserId),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'roleplayPosts' : IDL.Vec(RoleplayPost),
  'serverId' : ServerId,
});
export const ServerRole = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
  'owner' : IDL.Null,
});
export const ServerMembership = IDL.Record({
  'userId' : UserId,
  'role' : ServerRole,
});
export const Server = IDL.Record({
  'id' : ServerId,
  'owner' : UserId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'bannerImageUrl' : IDL.Opt(IDL.Text),
  'memberships' : IDL.Vec(ServerMembership),
  'rooms' : IDL.Vec(Room),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCharacterProfile' : IDL.Func([CharacterProfile], [], []),
  'createRoleplayPost' : IDL.Func([ServerId, RoomId, IDL.Text], [], []),
  'createRoom' : IDL.Func([ServerId, RoomId, IDL.Text, IDL.Text], [], []),
  'createServer' : IDL.Func(
      [ServerId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'deleteRoleplayPost' : IDL.Func([ServerId, RoomId, RoleplayPostId], [], []),
  'editCharacterProfile' : IDL.Func([CharacterProfile], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacterProfile' : IDL.Func(
      [CharacterId],
      [CharacterProfile],
      ['query'],
    ),
  'getRoleplayPost' : IDL.Func(
      [ServerId, RoomId, RoleplayPostId],
      [RoleplayPost],
      ['query'],
    ),
  'getRoom' : IDL.Func([ServerId, RoomId], [Room], ['query']),
  'getServer' : IDL.Func([ServerId], [Server], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinServer' : IDL.Func([ServerId], [], []),
  'leaveServer' : IDL.Func([ServerId], [], []),
  'listCharacterProfiles' : IDL.Func(
      [UserId, IDL.Opt(ServerId)],
      [IDL.Vec(CharacterProfile)],
      ['query'],
    ),
  'listRoleplayPosts' : IDL.Func(
      [ServerId, RoomId],
      [IDL.Vec(RoleplayPost)],
      ['query'],
    ),
  'listRooms' : IDL.Func([ServerId], [IDL.Vec(Room)], ['query']),
  'listServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
  'removeMember' : IDL.Func([ServerId, UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateServer' : IDL.Func(
      [ServerId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CharacterId = IDL.Text;
  const UserId = IDL.Principal;
  const ServerId = IDL.Text;
  const CharacterProfile = IDL.Record({
    'id' : CharacterId,
    'owner' : UserId,
    'appearance' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'avatarImageUrl' : IDL.Opt(IDL.Text),
    'serverId' : IDL.Opt(ServerId),
  });
  const RoomId = IDL.Text;
  const RoleplayPostId = IDL.Nat;
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const RoleplayPost = IDL.Record({
    'id' : RoleplayPostId,
    'content' : IDL.Text,
    'author' : UserId,
    'timestamp' : IDL.Int,
    'roomId' : RoomId,
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'creator' : UserId,
    'members' : IDL.Vec(UserId),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'roleplayPosts' : IDL.Vec(RoleplayPost),
    'serverId' : ServerId,
  });
  const ServerRole = IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'owner' : IDL.Null,
  });
  const ServerMembership = IDL.Record({
    'userId' : UserId,
    'role' : ServerRole,
  });
  const Server = IDL.Record({
    'id' : ServerId,
    'owner' : UserId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'bannerImageUrl' : IDL.Opt(IDL.Text),
    'memberships' : IDL.Vec(ServerMembership),
    'rooms' : IDL.Vec(Room),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCharacterProfile' : IDL.Func([CharacterProfile], [], []),
    'createRoleplayPost' : IDL.Func([ServerId, RoomId, IDL.Text], [], []),
    'createRoom' : IDL.Func([ServerId, RoomId, IDL.Text, IDL.Text], [], []),
    'createServer' : IDL.Func(
        [ServerId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'deleteRoleplayPost' : IDL.Func([ServerId, RoomId, RoleplayPostId], [], []),
    'editCharacterProfile' : IDL.Func([CharacterProfile], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacterProfile' : IDL.Func(
        [CharacterId],
        [CharacterProfile],
        ['query'],
      ),
    'getRoleplayPost' : IDL.Func(
        [ServerId, RoomId, RoleplayPostId],
        [RoleplayPost],
        ['query'],
      ),
    'getRoom' : IDL.Func([ServerId, RoomId], [Room], ['query']),
    'getServer' : IDL.Func([ServerId], [Server], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinServer' : IDL.Func([ServerId], [], []),
    'leaveServer' : IDL.Func([ServerId], [], []),
    'listCharacterProfiles' : IDL.Func(
        [UserId, IDL.Opt(ServerId)],
        [IDL.Vec(CharacterProfile)],
        ['query'],
      ),
    'listRoleplayPosts' : IDL.Func(
        [ServerId, RoomId],
        [IDL.Vec(RoleplayPost)],
        ['query'],
      ),
    'listRooms' : IDL.Func([ServerId], [IDL.Vec(Room)], ['query']),
    'listServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
    'removeMember' : IDL.Func([ServerId, UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateServer' : IDL.Func(
        [ServerId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };